### ISSUE TITLE
ITC Land (Artillery creates a drone) issue

### ISSUE THREAD

**Issue by CE-Modding** [FatLurch/FFA#1]
When using ITC Land, where that mod creates a drone in order to have artillery be able to be shot down, this mod attempts to create FRIES on drones. 
this happens on every drone created. adding upto several seconds of microlag. 

**Possibility to add all drones to the fries blacklist?**

**Comment by FatLurch** [comment]
Thanks for the well-written feedback!

I'll see if I can blacklist specific vehicles. I know BIS defined one of the early drones as a helicopter instead of a UAV in the config.

If I'm not able to blacklist I'll coordinate with Yax to use any other drone.

**Comment by FatLurch** [comment]
@Eagle-Studios 

I've updated this with a blacklist for ["B_UAV_01_F", "B_UAV_06_F", "B_UAV_06_medical_F"]. Please let me know if this resolves the issue you've been seeing.

Thanks

**Comment by CE-Modding** [comment]
seems to be working fine.
